# Copyright 2026 Tencent
# SPDX-License-Identifier: BSD-3-Clause

PASS = "PASS"
EXPORT_UNSUPPORTED = "EXPORT_UNSUPPORTED"
PT2_FRONTEND_UNSUPPORTED = "PT2_FRONTEND_UNSUPPORTED"
PNNX_LOWERING_UNSUPPORTED = "PNNX_LOWERING_UNSUPPORTED"
NUMERICAL_MISMATCH = "NUMERICAL_MISMATCH"
UNCLASSIFIED = "UNCLASSIFIED"


# Each pt2 test must have an explicit expected category.  A non-PASS entry must
# also provide a stable diagnostic substring so that unrelated regressions do
# not become expected failures accidentally.
PT2_EXPECTATIONS = {
    "test_F_adaptive_avg_pool1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.adaptive_avg_pool1d.default"),
    "test_F_adaptive_avg_pool2d": (PASS, ""),
    "test_F_adaptive_avg_pool3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.adaptive_avg_pool3d.default"),
    "test_F_adaptive_max_pool1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.adaptive_max_pool1d.default"),
    "test_F_adaptive_max_pool2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.adaptive_max_pool2d.default"),
    "test_F_adaptive_max_pool3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.adaptive_max_pool3d.default"),
    "test_F_affine_grid": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.affine_grid_generator.default"),
    "test_F_alpha_dropout": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.alpha_dropout.default"),
    "test_F_avg_pool1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.avg_pool1d.default"),
    "test_F_avg_pool2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.avg_pool2d.default"),
    "test_F_avg_pool3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.avg_pool3d.default"),
    "test_F_batch_norm": (PASS, ""),
    "test_F_celu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_conv1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.conv1d.default"),
    "test_F_conv2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.conv2d.padding"),
    "test_F_conv3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.conv3d.default"),
    "test_F_conv_transpose1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.conv_transpose1d.default"),
    "test_F_conv_transpose2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.conv_transpose2d.input"),
    "test_F_conv_transpose3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.conv_transpose3d.input"),
    "test_F_dropout": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.dropout.default"),
    "test_F_dropout2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.feature_dropout.default"),
    "test_F_dropout3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.feature_dropout.default"),
    "test_F_elu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_embedding": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.embedding.default"),
    "test_F_feature_alpha_dropout": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.feature_alpha_dropout.default"),
    "test_F_fold": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.col2im.default"),
    "test_F_gelu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_glu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.glu.default"),
    "test_F_grid_sample": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_group_norm": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.group_norm.default"),
    "test_F_hardshrink": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_hardsigmoid": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_hardswish": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_hardtanh": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_instance_norm": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.instance_norm.default"),
    "test_F_interpolate": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.upsample_nearest1d.vec"),
    "test_F_layer_norm": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.layer_norm.default"),
    "test_F_leaky_relu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_linear": (PASS, ""),
    "test_F_local_response_norm": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_log_softmax": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_logsigmoid": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_lp_pool1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.pow.Tensor_Scalar"),
    "test_F_lp_pool2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.pow.Tensor_Scalar"),
    "test_F_max_pool1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.max_pool1d.default"),
    "test_F_max_pool2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.max_pool2d_with_indices.default"),
    "test_F_max_pool3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.max_pool3d.default"),
    "test_F_mish": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_normalize": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.linalg_vector_norm.default"),
    "test_F_pad": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.pad.default"),
    "test_F_pairwise_distance": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.pairwise_distance.default"),
    "test_F_pixel_shuffle": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.pixel_shuffle.default"),
    "test_F_pixel_unshuffle": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.pixel_unshuffle.default"),
    "test_F_prelu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_relu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_relu6": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_rms_norm": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.rms_norm.default"),
    "test_F_rrelu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_scaled_dot_product_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.scaled_dot_product_attention.default"),
    "test_F_selu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_sigmoid": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_silu": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_softmax": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_softmin": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_softplus": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_softshrink": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_softsign": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_tanh": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_tanhshrink": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_threshold": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.mul.Tensor"),
    "test_F_unfold": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.im2col.default"),
    "test_F_upsample": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.upsample_nearest1d.vec"),
    "test_F_upsample_bilinear": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.upsample_bilinear2d.vec"),
    "test_F_upsample_nearest": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.upsample_nearest2d.vec"),
    "test_Tensor_reshape": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.reshape.default"),
    "test_nn_Conv2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.conv2d.padding"),
    "test_nn_Linear": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten._weight_norm.default"),
    "test_torch_flatten": (PASS, ""),
}
