# Copyright 2026 Tencent
# SPDX-License-Identifier: BSD-3-Clause

PASS = "PASS"
EXPORT_UNSUPPORTED = "EXPORT_UNSUPPORTED"
PT2_FRONTEND_UNSUPPORTED = "PT2_FRONTEND_UNSUPPORTED"
PNNX_LOWERING_UNSUPPORTED = "PNNX_LOWERING_UNSUPPORTED"
NUMERICAL_MISMATCH = "NUMERICAL_MISMATCH"
UNCLASSIFIED = "UNCLASSIFIED"


# Each pt2 test must have an explicit expected category.  A non-PASS entry must
# also provide a stable diagnostic substring so that unrelated regressions do
# not become expected failures accidentally.
PT2_EXPECTATIONS = {
    "test_F_adaptive_avg_pool1d": (PASS, ""),
    "test_F_adaptive_avg_pool2d": (PASS, ""),
    "test_F_adaptive_avg_pool3d": (PASS, ""),
    "test_F_adaptive_max_pool1d": (PASS, ""),
    "test_F_adaptive_max_pool2d": (PASS, ""),
    "test_F_adaptive_max_pool3d": (PASS, ""),
    "test_F_affine_grid": (PASS, ""),
    "test_F_alpha_dropout": (PASS, ""),
    "test_F_avg_pool1d": (PNNX_LOWERING_UNSUPPORTED, "############# pass_ncnn"),
    "test_F_avg_pool2d": (PNNX_LOWERING_UNSUPPORTED, "unsupported avgpool2d divisor_override"),
    "test_F_avg_pool3d": (PNNX_LOWERING_UNSUPPORTED, "unsupported avgpool3d divisor_override"),
    "test_F_batch_norm": (PASS, ""),
    "test_F_celu": (PASS, ""),
    "test_F_conv1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv1d.padding"),
    "test_F_conv2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv2d.padding"),
    "test_F_conv3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv3d.padding"),
    "test_F_conv_transpose1d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_F_conv_transpose2d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_F_conv_transpose3d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_F_dropout": (PASS, ""),
    "test_F_dropout2d": (PASS, ""),
    "test_F_dropout3d": (PASS, ""),
    "test_F_elu": (PASS, ""),
    "test_F_embedding": (PASS, ""),
    "test_F_feature_alpha_dropout": (PASS, ""),
    "test_F_fold": (PASS, ""),
    "test_F_gelu": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument approximate for torch.ops.aten.gelu.default"),
    "test_F_glu": (PASS, ""),
    "test_F_grid_sample": (PASS, ""),
    "test_F_group_norm": (PASS, ""),
    "test_F_hardshrink": (PASS, ""),
    "test_F_hardsigmoid": (PASS, ""),
    "test_F_hardswish": (PASS, ""),
    "test_F_hardtanh": (PASS, ""),
    "test_F_instance_norm": (PASS, ""),
    "test_F_interpolate": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_nearest1d.vec"),
    "test_F_layer_norm": (PASS, ""),
    "test_F_leaky_relu": (PASS, ""),
    "test_F_linear": (PASS, ""),
    "test_F_local_response_norm": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_F_log_softmax": (PASS, ""),
    "test_F_logsigmoid": (PASS, ""),
    "test_F_lp_pool1d": (PASS, ""),
    "test_F_lp_pool2d": (PASS, ""),
    "test_F_max_pool1d": (PNNX_LOWERING_UNSUPPORTED, "############# pass_ncnn"),
    "test_F_max_pool2d": (PNNX_LOWERING_UNSUPPORTED, "############# pass_ncnn"),
    "test_F_max_pool3d": (PNNX_LOWERING_UNSUPPORTED, "############# pass_ncnn"),
    "test_F_mish": (PASS, ""),
    "test_F_normalize": (PASS, ""),
    "test_F_pad": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_F_pairwise_distance": (PASS, ""),
    "test_F_pixel_shuffle": (PASS, ""),
    "test_F_pixel_unshuffle": (PASS, ""),
    "test_F_prelu": (PASS, ""),
    "test_F_relu": (PASS, ""),
    "test_F_relu6": (PASS, ""),
    "test_F_rms_norm": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten._assert_tensor_metadata.default"),
    "test_F_rrelu": (PASS, ""),
    "test_F_scaled_dot_product_attention": (PASS, ""),
    "test_F_selu": (PASS, ""),
    "test_F_sigmoid": (PASS, ""),
    "test_F_silu": (PASS, ""),
    "test_F_softmax": (PASS, ""),
    "test_F_softmin": (PASS, ""),
    "test_F_softplus": (PASS, ""),
    "test_F_softshrink": (PASS, ""),
    "test_F_softsign": (PASS, ""),
    "test_F_tanh": (PASS, ""),
    "test_F_tanhshrink": (PASS, ""),
    "test_F_threshold": (PASS, ""),
    "test_F_unfold": (PASS, ""),
    "test_F_upsample": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_nearest1d.vec"),
    "test_F_upsample_bilinear": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_bilinear2d.vec"),
    "test_F_upsample_nearest": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_nearest2d.vec"),
    "test_Tensor_expand": (PASS, ""),
    "test_Tensor_fill": (PASS, ""),
    "test_Tensor_index": (EXPORT_UNSUPPORTED, "PendingUnbackedSymbolNotFound: Pending unbacked symbols"),
    "test_Tensor_index_put": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument indices for torch.ops.aten.index_put.default"),
    "test_Tensor_masked_fill": (PASS, ""),
    "test_Tensor_new_empty": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.new_empty.default"),
    "test_Tensor_new_full": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.new_full.default"),
    "test_Tensor_new_ones": (PASS, ""),
    "test_Tensor_new_zeros": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.new_zeros.default"),
    "test_Tensor_permute": (PASS, ""),
    "test_Tensor_repeat": (PASS, ""),
    "test_Tensor_reshape": (PASS, ""),
    "test_Tensor_reshape_as": (PASS, ""),
    "test_Tensor_select": (PASS, ""),
    "test_Tensor_slice": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_Tensor_slice_copy": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_Tensor_to": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten._assert_tensor_metadata.default"),
    "test_Tensor_type_as": (PASS, ""),
    "test_Tensor_unflatten": (PASS, ""),
    "test_Tensor_view": (PASS, ""),
    "test_nn_AdaptiveAvgPool1d": (PASS, ""),
    "test_nn_AdaptiveAvgPool2d": (PASS, ""),
    "test_nn_AdaptiveAvgPool3d": (PASS, ""),
    "test_nn_AdaptiveMaxPool1d": (PASS, ""),
    "test_nn_AdaptiveMaxPool2d": (PASS, ""),
    "test_nn_AdaptiveMaxPool3d": (PASS, ""),
    "test_nn_AlphaDropout": (PASS, ""),
    "test_nn_AvgPool1d": (PASS, ""),
    "test_nn_AvgPool2d": (PASS, ""),
    "test_nn_AvgPool3d": (PASS, ""),
    "test_nn_BatchNorm1d": (PASS, ""),
    "test_nn_BatchNorm2d": (PASS, ""),
    "test_nn_BatchNorm3d": (PASS, ""),
    "test_nn_CELU": (PASS, ""),
    "test_nn_ChannelShuffle": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_ConstantPad1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_ConstantPad2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_ConstantPad3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_Conv1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv1d.padding"),
    "test_nn_Conv2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv2d.padding"),
    "test_nn_Conv3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv3d.padding"),
    "test_nn_ConvTranspose1d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_ConvTranspose2d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_ConvTranspose3d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_Dropout": (PASS, ""),
    "test_nn_Dropout2d": (PASS, ""),
    "test_nn_Dropout3d": (PASS, ""),
    "test_nn_ELU": (PASS, ""),
    "test_nn_Embedding": (PASS, ""),
    "test_nn_Fold": (PASS, ""),
    "test_nn_GELU": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument approximate for torch.ops.aten.gelu.default"),
    "test_nn_GLU": (PASS, ""),
    "test_nn_GRU": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.zeros.default"),
    "test_nn_GroupNorm": (PASS, ""),
    "test_nn_Hardshrink": (PASS, ""),
    "test_nn_Hardsigmoid": (PASS, ""),
    "test_nn_Hardswish": (PASS, ""),
    "test_nn_Hardtanh": (PASS, ""),
    "test_nn_Identity": (PASS, ""),
    "test_nn_InstanceNorm1d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_InstanceNorm2d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_InstanceNorm3d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_LPPool1d": (PASS, ""),
    "test_nn_LPPool2d": (PASS, ""),
    "test_nn_LSTM": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.zeros.default"),
    "test_nn_LayerNorm": (PASS, ""),
    "test_nn_LeakyReLU": (PASS, ""),
    "test_nn_Linear": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_nn_LocalResponseNorm": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_LogSigmoid": (PASS, ""),
    "test_nn_LogSoftmax": (PASS, ""),
    "test_nn_MaxPool1d": (PASS, ""),
    "test_nn_MaxPool2d": (PASS, ""),
    "test_nn_MaxPool3d": (PASS, ""),
    "test_nn_Mish": (PASS, ""),
    "test_nn_MultiheadAttention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor output for torch.ops.aten.chunk.default"),
    "test_nn_PReLU": (PASS, ""),
    "test_nn_PixelShuffle": (PASS, ""),
    "test_nn_PixelUnshuffle": (PASS, ""),
    "test_nn_RMSNorm": (PASS, ""),
    "test_nn_RNN": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.zeros.default"),
    "test_nn_RReLU": (PASS, ""),
    "test_nn_ReLU": (PASS, ""),
    "test_nn_ReLU6": (PASS, ""),
    "test_nn_ReflectionPad1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_ReflectionPad2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_ReplicationPad1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_ReplicationPad2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_ReplicationPad3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_nn_SELU": (PASS, ""),
    "test_nn_SiLU": (PASS, ""),
    "test_nn_Sigmoid": (PASS, ""),
    "test_nn_Softmax": (PASS, ""),
    "test_nn_Softmax2d": (PASS, ""),
    "test_nn_Softmin": (PASS, ""),
    "test_nn_Softplus": (PASS, ""),
    "test_nn_Softshrink": (PASS, ""),
    "test_nn_Softsign": (PASS, ""),
    "test_nn_Tanh": (PASS, ""),
    "test_nn_Tanhshrink": (PASS, ""),
    "test_nn_Threshold": (PASS, ""),
    "test_nn_Unfold": (PASS, ""),
    "test_nn_Upsample": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_nearest1d.vec"),
    "test_nn_UpsamplingBilinear2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_bilinear2d.vec"),
    "test_nn_UpsamplingNearest2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_nearest2d.vec"),
    "test_nn_ZeroPad2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_torch_abs": (PASS, ""),
    "test_torch_acos": (PASS, ""),
    "test_torch_acosh": (PASS, ""),
    "test_torch_addmm": (PASS, ""),
    "test_torch_amax": (PASS, ""),
    "test_torch_amin": (PASS, ""),
    "test_torch_arange": (EXPORT_UNSUPPORTED, "GuardOnDataDependentSymNode: Could not guard on data-dependent expression"),
    "test_torch_argmax": (PASS, ""),
    "test_torch_argmin": (PASS, ""),
    "test_torch_asin": (PASS, ""),
    "test_torch_asinh": (PASS, ""),
    "test_torch_atan": (PASS, ""),
    "test_torch_atan2": (PASS, ""),
    "test_torch_atanh": (PASS, ""),
    "test_torch_bitwise_and": (PASS, ""),
    "test_torch_bitwise_left_shift": (PASS, ""),
    "test_torch_bitwise_not": (PASS, ""),
    "test_torch_bitwise_or": (PASS, ""),
    "test_torch_bitwise_right_shift": (PASS, ""),
    "test_torch_bitwise_xor": (PASS, ""),
    "test_torch_bmm": (PASS, ""),
    "test_torch_cat": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument tensors for torch.ops.aten.cat.default"),
    "test_torch_ceil": (PASS, ""),
    "test_torch_chunk": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor output for torch.ops.aten.chunk.default"),
    "test_torch_clamp": (PASS, ""),
    "test_torch_clone": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.clone.default"),
    "test_torch_complex": (PASS, ""),
    "test_torch_cos": (PASS, ""),
    "test_torch_cosh": (PASS, ""),
    "test_torch_cross": (PASS, ""),
    "test_torch_cumprod": (PASS, ""),
    "test_torch_cumsum": (PASS, ""),
    "test_torch_diag": (PASS, ""),
    "test_torch_einsum": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument equation for torch.ops.aten.einsum.default"),
    "test_torch_eq": (PASS, ""),
    "test_torch_exp": (PASS, ""),
    "test_torch_expm1": (PASS, ""),
    "test_torch_fft_fft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_fft.default"),
    "test_torch_fft_fft2": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_fft2.default"),
    "test_torch_fft_fftn": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_fftn.default"),
    "test_torch_fft_hfft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_hfft.default"),
    "test_torch_fft_hfft2": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_hfft2.default"),
    "test_torch_fft_hfftn": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_hfftn.default"),
    "test_torch_fft_ifft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_ifft.default"),
    "test_torch_fft_ifft2": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_ifft2.default"),
    "test_torch_fft_ifftn": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_ifftn.default"),
    "test_torch_fft_ihfft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_ihfft.default"),
    "test_torch_fft_ihfft2": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_ihfft2.default"),
    "test_torch_fft_ihfftn": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_ihfftn.default"),
    "test_torch_fft_irfft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_irfft.default"),
    "test_torch_fft_irfft2": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_irfft2.default"),
    "test_torch_fft_irfftn": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_irfftn.default"),
    "test_torch_fft_rfft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_rfft.default"),
    "test_torch_fft_rfft2": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_rfft2.default"),
    "test_torch_fft_rfftn": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument norm for torch.ops.aten.fft_rfftn.default"),
    "test_torch_flatten": (PASS, ""),
    "test_torch_flip": (PASS, ""),
    "test_torch_floor": (PASS, ""),
    "test_torch_full": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.full.default"),
    "test_torch_full_like": (PASS, ""),
    "test_torch_gather": (PASS, ""),
    "test_torch_ge": (PASS, ""),
    "test_torch_gt": (PASS, ""),
    "test_torch_imag": (PASS, ""),
    "test_torch_index_select": (PASS, ""),
    "test_torch_istft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.hann_window.default"),
    "test_torch_le": (PASS, ""),
    "test_torch_lgamma": (PASS, ""),
    "test_torch_log": (PASS, ""),
    "test_torch_log10": (PASS, ""),
    "test_torch_log1p": (PASS, ""),
    "test_torch_logaddexp": (PASS, ""),
    "test_torch_logical_and": (PASS, ""),
    "test_torch_logical_not": (PASS, ""),
    "test_torch_logical_or": (PASS, ""),
    "test_torch_logical_xor": (PASS, ""),
    "test_torch_logsumexp": (PASS, ""),
    "test_torch_lt": (PASS, ""),
    "test_torch_masked_select": (PT2_FRONTEND_UNSUPPORTED, "dynamic tensor metadata is unsupported"),
    "test_torch_matmul": (PASS, ""),
    "test_torch_max": (PASS, ""),
    "test_torch_maximum": (PASS, ""),
    "test_torch_mean": (PASS, ""),
    "test_torch_min": (PASS, ""),
    "test_torch_minimum": (PASS, ""),
    "test_torch_narrow": (PASS, ""),
    "test_torch_ne": (PASS, ""),
    "test_torch_neg": (PASS, ""),
    "test_torch_norm": (PASS, ""),
    "test_torch_ones": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.ones.default"),
    "test_torch_ones_like": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.ones_like.default"),
    "test_torch_positive": (PASS, ""),
    "test_torch_pow": (PASS, ""),
    "test_torch_prod": (PASS, ""),
    "test_torch_real": (PASS, ""),
    "test_torch_reciprocal": (PASS, ""),
    "test_torch_repeat_interleave": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_torch_roll": (PASS, ""),
    "test_torch_round": (PASS, ""),
    "test_torch_rsqrt": (PASS, ""),
    "test_torch_scatter_add": (PASS, ""),
    "test_torch_sign": (PASS, ""),
    "test_torch_sin": (PASS, ""),
    "test_torch_sinh": (PASS, ""),
    "test_torch_slice_scatter": (PASS, ""),
    "test_torch_split": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor output for torch.ops.aten.split.Tensor"),
    "test_torch_sqrt": (PASS, ""),
    "test_torch_square": (PASS, ""),
    "test_torch_squeeze": (PASS, ""),
    "test_torch_stack": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument tensors for torch.ops.aten.stack.default"),
    "test_torch_std": (PASS, ""),
    "test_torch_stft": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.hann_window.default"),
    "test_torch_sum": (PASS, ""),
    "test_torch_t": (PASS, ""),
    "test_torch_tan": (PASS, ""),
    "test_torch_tanh": (PASS, ""),
    "test_torch_tensor_split": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor output for torch.ops.aten.tensor_split.indices"),
    "test_torch_tile": (PASS, ""),
    "test_torch_topk": (PASS, ""),
    "test_torch_transpose": (PASS, ""),
    "test_torch_trunc": (PASS, ""),
    "test_torch_unbind": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor output for torch.ops.aten.unbind.int"),
    "test_torch_unsqueeze": (PASS, ""),
    "test_torch_view_as_complex": (PASS, ""),
    "test_torch_view_as_real": (PASS, ""),
    "test_torch_where": (PASS, ""),
    "test_torch_zeros": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.zeros.default"),
    "test_torch_zeros_like": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.zeros_like.default"),
    "test_torch_mm": (PASS, ""),
    "test_torch_mv": (PASS, ""),
    "test_convnext_tiny": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument approximate for torch.ops.aten.gelu.default"),
    "test_ir_complex": (PT2_FRONTEND_UNSUPPORTED, "torch 2.12.1+cu126 aten opset 10 target torch.ops.aten.sub.Tensor: unsupported serialized argument as_complex for other"),
    "test_mobilenet_v2": (PASS, ""),
    "test_mobilenet_v3_small": (PASS, ""),
    "test_pnnx_eliminate_noop_cat": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument tensors for torch.ops.aten.cat.default"),
    "test_pnnx_eliminate_noop_expand": (PASS, ""),
    "test_pnnx_eliminate_noop_math": (PASS, ""),
    "test_pnnx_eliminate_noop_upsample": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_nearest2d.vec"),
    "test_pnnx_expression": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor output for torch.ops.aten.unbind.int"),
    "test_pnnx_fold_constant": (PASS, ""),
    "test_pnnx_fuse_adjacent_permute": (PASS, ""),
    "test_pnnx_fuse_adjacent_reshape": (PASS, ""),
    "test_pnnx_fuse_asymmetric_pad_conv2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_pnnx_fuse_channel_shuffle": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument tensors for torch.ops.aten.cat.default"),
    "test_pnnx_fuse_conv1d_batchnorm1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv1d.padding"),
    "test_pnnx_fuse_conv2d_batchnorm2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv2d.padding"),
    "test_pnnx_fuse_conv3d_batchnorm3d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument padding for torch.ops.aten.conv3d.padding"),
    "test_pnnx_fuse_convtranspose1d_batchnorm1d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_pnnx_fuse_convtranspose2d_batchnorm2d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_pnnx_fuse_convtranspose3d_batchnorm3d": (PNNX_LOWERING_UNSUPPORTED, "SyntaxError: invalid syntax"),
    "test_pnnx_fuse_input_unpack": (PASS, ""),
    "test_pnnx_fuse_layernorm": (PASS, ""),
    "test_pnnx_fuse_linear_batchnorm1d": (PASS, ""),
    "test_pnnx_fuse_multiheadattention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument equation for torch.ops.aten.einsum.default"),
    "test_pnnx_fuse_pad_conv1d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_pnnx_fuse_pad_conv2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_pnnx_fuse_pixel_shuffle": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_pnnx_fuse_pixel_unshuffle": (PASS, ""),
    "test_pnnx_fuse_rmsnorm": (PASS, ""),
    "test_pnnx_fuse_scaled_dot_product_attention": (PASS, ""),
    "test_pnnx_fuse_select_to_unbind": (PASS, ""),
    "test_pnnx_fuse_slice_to_tensor_split": (PASS, ""),
    "test_pnnx_input_npy": (NUMERICAL_MISMATCH, "output mismatch"),
    "test_pnnx_model_stat": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument scale_factors for torch.ops.aten.upsample_nearest2d.vec"),
    "test_quantization_shufflenet_v2_x1_0": (EXPORT_UNSUPPORTED, "Conv2dPackedParamsBase"),
    "test_resnet18": (PASS, ""),
    "test_shufflenet_v2_x1_0": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument tensors for torch.ops.aten.cat.default"),
    "test_squeezenet1_1": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument tensors for torch.ops.aten.cat.default"),
    "test_swin_t": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument indices for torch.ops.aten.index.Tensor"),
    "test_torchaudio_F_inverse_spectrogram": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.hann_window.default"),
    "test_torchaudio_F_spectrogram": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.hann_window.default"),
    "test_torchaudio_InverseSpectrogram": (PASS, ""),
    "test_torchaudio_Spectrogram": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument mode for torch.ops.aten.pad.default"),
    "test_torchvision_DeformConv2d": (PT2_FRONTEND_UNSUPPORTED, "unsupported exported operator torch.ops.aten.zeros.default"),
    "test_torchvision_RoIAlign": (PT2_FRONTEND_UNSUPPORTED, "exported operator target must start with torch.ops.aten"),
    "test_transformers_albert_attention": (PASS, ""),
    "test_transformers_bart_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_bert_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_bert_generation_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_blenderbot_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_camembert_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_chinese_clip_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.softmax.int"),
    "test_transformers_clip_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.softmax.int"),
    "test_transformers_ctrl_attention": (PASS, ""),
    "test_transformers_deberta_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor output for torch.ops.aten.chunk.default"),
    "test_transformers_deepseek_v3_attention": (PT2_FRONTEND_UNSUPPORTED, "named argument name must not be empty"),
    "test_transformers_distilbert_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_electra_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_flaubert_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten._assert_tensor_metadata.default"),
    "test_transformers_fsmt_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_funnel_attention": (PT2_FRONTEND_UNSUPPORTED, "dynamic tensor metadata is unsupported"),
    "test_transformers_gpt2_attention": (PT2_FRONTEND_UNSUPPORTED, "buffer attn0.bias is present in constants config"),
    "test_transformers_layoutlm_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten.softmax.int"),
    "test_transformers_longformer_attention": (PT2_FRONTEND_UNSUPPORTED, "inputs[1].arg.as_float: expected float"),
    "test_transformers_lxmert_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_m2m_100_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_marian_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_mbart_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_mobilebert_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_mt5_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.arange.default"),
    "test_transformers_openai_attention": (PT2_FRONTEND_UNSUPPORTED, "buffer attn0.bias is present in constants config"),
    "test_transformers_pegasus_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_prophetnet_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument equation for torch.ops.aten.einsum.default"),
    "test_transformers_qwen2_attention": (PT2_FRONTEND_UNSUPPORTED, "named argument name must not be empty"),
    "test_transformers_qwen3_attention": (PT2_FRONTEND_UNSUPPORTED, "named argument name must not be empty"),
    "test_transformers_reformer_attention": (PT2_FRONTEND_UNSUPPORTED, "buffer attn0.self_attention.mask_value_float16 is present in constants config"),
    "test_transformers_roberta_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_squeezebert_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_t5_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument device for torch.ops.aten.arange.default"),
    "test_transformers_xlm_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument dtype for torch.ops.aten._assert_tensor_metadata.default"),
    "test_transformers_xlm_roberta_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument memory_format for torch.ops.aten.contiguous.default"),
    "test_transformers_xlnet_attention": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument equation for torch.ops.aten.einsum.default"),
    "test_vit_b_32": (PT2_FRONTEND_UNSUPPORTED, "unsupported non-tensor argument tensors for torch.ops.aten.cat.default"),
}
